- netbout-web/src/main/java/com/netbout/rest/TkStart.java
- netbout-web/src/test/java/com/netbout/rest/bout/TkStartTest.java
Proposed fix for issue #610 – `TkStart` now checks if 'post' and 'invite' parameters are specified and performs required actions. `TkStartTest.postsMessageAndInvitesFriends` added.
> #610 /start with arguments

- .rultor.yml
* removed site deployment according https://github.com/yegor256/netbout/issues/577#issuecomment-105406368
> #577 site deployment off

- netbout-client/src/main/java/com/netbout/mock/MkInbox.java
- netbout-client/src/test/java/com/netbout/mock/MkInboxTest.java
- netbout-web/src/test/java/com/netbout/email/EmAliasTest.java
- netbout-web/src/test/java/com/netbout/rest/bout/TkStartTest.java
#570: invite inside of start() and remove one invitation in test
> #570: invite inside of start() and remove one invitation in test

- netbout-client/src/main/java/com/netbout/client/RtAlias.java
- netbout-client/src/main/java/com/netbout/client/RtUser.java
- netbout-client/src/test/java/com/netbout/client/RtAliasITCase.java
Fixes #611 
Simply implemented ```RtAlias.email()``` and ```RtAlias.email(final String email)``` methods taking inspiration from other Rt* classes.
> #611 RtAlias.email not implemented yet

- netbout-web/src/main/java/com/netbout/rest/RsReturn.java
- netbout-web/src/main/java/com/netbout/rest/TkReturn.java
- netbout-web/src/test/java/com/netbout/rest/TkAppTest.java
Fix for issue #646. Added explicit setting of cookie path in `RsReturn`, and decoding of cookie value in `TkReturn`
> #646 return-after-login feature

- est/first.est
Proposed fix for issue #576. That's a completely a wild guess, not sure whether it is useful.
> #576 Provide project estimate

- netbout-web/src/main/java/com/netbout/dynamo/DyAliases.java
For #627 
changed the error message
> #627 Incomplete alias check

- netbout-web/src/main/java/com/netbout/misc/Ports.java
- netbout-web/src/main/java/com/netbout/misc/package-info.java
- netbout-web/src/test/java/com/netbout/misc/PortsTest.java
- netbout-web/src/test/java/com/netbout/misc/package-info.java
Copied Ports class from the Takes project as requested on issue #615.
> Copied Ports class from the Takes project. Issue #615

- netbout-web/src/main/java/com/netbout/rest/bout/TkPost.java
#616 just changed the throwen exception class that was wrong
> #616: change throwed exception class

- netbout-web/src/main/java/com/netbout/email/EmMessages.java
Added a random number at the end of the URL, so that will make Google don't hide that piece of code. Issue #541
> Added a random number at the end of the URL, so gmail don't hide the url. Issue #541

- .gitignore
- netbout-web/src/main/java/com/netbout/rest/TkApp.java
- netbout-web/src/main/java/com/netbout/rest/TkAppAuth.java
- netbout-web/src/test/java/com/netbout/rest/TkAppTest.java
Fixed puzzle `609-bc8eaf9f` to execute the test that redirects an anonymous user to login page. Issue #648
> Fixed puzzle to execute the test that redirects an anonymous user to login page. Issue #648

- netbout-web/src/main/java/com/netbout/rest/TkInbox.java
- netbout-web/src/test/java/com/netbout/rest/TkInboxTest.java
Fixed kick URL that was reported on issue #620.
> Fixed kick URL. Issue #620

- netbout-web/src/main/js/bout.js
Add a JQuery fn to avoid multiple submission of the same form and attached to the *Post message* form.
Fixes #567
> #567 prevent duplicate messages in bouts

- netbout-client/src/main/java/com/netbout/client/RtBout.java
- netbout-client/src/main/java/com/netbout/client/cached/CdBout.java
- netbout-client/src/main/java/com/netbout/client/retry/ReBout.java
- netbout-client/src/main/java/com/netbout/mock/H2Sql.java
- netbout-client/src/main/java/com/netbout/mock/MkBout.java
- netbout-spi/src/main/java/com/netbout/spi/Bout.java
- netbout-web/src/main/java/com/netbout/cached/CdBout.java
- netbout-web/src/main/java/com/netbout/dynamo/DyBout.java
- netbout-web/src/main/java/com/netbout/dynamo/DyFriends.java
- netbout-web/src/main/java/com/netbout/dynamo/DyInbox.java
- netbout-web/src/main/java/com/netbout/email/EmBout.java
- netbout-web/src/main/java/com/netbout/email/EmMessages.java
- netbout-web/src/main/java/com/netbout/rest/bout/TkIndex.java
- netbout-web/src/main/java/com/netbout/rest/bout/TkSubscribe.java
- netbout-web/src/main/xsl/bout.xsl
- netbout-web/src/main/xsl/layout.xsl
- netbout-web/src/test/java/com/netbout/dynamo/DyBoutITCase.java
Implemented Email subscription settings for individual bout #547
> Fixed #547 : Email subscription settings for individual bouts

- netbout-web/src/main/js/bout.js
- netbout-web/src/main/js/inbox.js
Fixed infinite scrolling problem on inbox and bout page for firefox #632
> Fixed #632: infinite scrolling problem on firefox

- netbout-client/src/main/java/com/netbout/client/RtInbox.java
- netbout-client/src/main/java/com/netbout/client/RtMessages.java
- netbout-client/src/main/java/com/netbout/client/cached/CdInbox.java
- netbout-client/src/main/java/com/netbout/client/cached/CdMessages.java
- netbout-client/src/main/java/com/netbout/client/retry/ReInbox.java
- netbout-client/src/main/java/com/netbout/client/retry/ReMessages.java
- netbout-client/src/main/java/com/netbout/mock/MkInbox.java
- netbout-client/src/main/java/com/netbout/mock/MkMessages.java
- netbout-spi/src/main/java/com/netbout/spi/Inbox.java
- netbout-spi/src/main/java/com/netbout/spi/Searchable.java
- netbout-web/src/main/java/com/netbout/cached/CdInbox.java
- netbout-web/src/main/java/com/netbout/cached/CdMessages.java
- netbout-web/src/main/java/com/netbout/dynamo/DyInbox.java
- netbout-web/src/main/java/com/netbout/dynamo/DyMessages.java
- netbout-web/src/main/java/com/netbout/email/EmInbox.java
- netbout-web/src/main/java/com/netbout/email/EmMessages.java
- netbout-web/src/main/java/com/netbout/rest/TkInbox.java
- netbout-web/src/main/java/com/netbout/rest/bout/TkIndex.java
- netbout-web/src/test/java/com/netbout/dynamo/DyInboxITCase.java
- netbout-web/src/test/java/com/netbout/dynamo/DyMessagesITCase.java
Fix for issue #603
- Added `Searchable<T> { Iterable<T> search(String term) }` interface to Inbox and Messages
- Initial implementation in all classes implementing `Inbox` and `Messages`
- Created two integration tests for dynamodb
- Added 2 todos to implement the UI
> #603 added search to inbox and messages

- netbout-client/src/test/java/com/netbout/mock/MkUserTest.java
for #707 
removed once used variable
> #707 reduced variables

- netbout-web/pom.xml
- netbout-web/src/test/java/com/netbout/rest/MarkdownTest.java
For #718 
* fixed pom.xml for run casperjs on windows
* fixed a broken test on windows
> #718 fixes the build issues on windows

- netbout-client/src/main/java/com/netbout/mock/MkBase.java
- netbout-client/src/main/java/com/netbout/mock/MkFriends.java
- netbout-client/src/test/java/com/netbout/mock/MkFriendsTest.java
- netbout-client/src/test/java/com/netbout/mock/MkInboxTest.java
Checked alias before invite operation and throw exception if it is not exist 
issue detail: #628
> #628 MkFriends.invite never fails

- netbout-web/src/main/js/bout.js
- netbout-web/src/main/xsl/bout.xsl
- netbout-web/src/test/casperjs/navigate-to-old-message-on-bout.js
Added link to message. (Issue #643)
> Added link to message. (Issue #643)

- netbout-web/src/main/java/com/netbout/rest/bout/TkBout.java
- netbout-web/src/main/java/com/netbout/rest/bout/TkIndex.java
- netbout-web/src/test/java/com/netbout/rest/bout/TkIndexTest.java
Bout page search box is searching messages, see details on #702
> #702 fixed search bout messages

- netbout-web/src/main/java/com/netbout/rest/bout/TkIndex.java
- netbout-web/src/main/java/com/netbout/rest/bout/TkPreview.java
- netbout-web/src/main/js/bout.js
- netbout-web/src/main/scss/bout.scss
- netbout-web/src/main/scss/preview.scss
- netbout-web/src/main/xsl/bout.xsl
- netbout-web/src/test/java/com/netbout/rest/TkPreviewTest.java
Added preview tab. (Issue #614)
As I said on issue, this issue depends on #728 to work properly.
> Added preview tab (Issue #614)

- netbout-web/src/main/js/bout.js
- netbout-web/src/test/casperjs/navigate-to-old-message-on-bout.js
Fixed JS that was loading message in wrong order. (Issue #728).
> Fixed JS that was loading message in wrong order. (Issue #728)

- netbout-web/src/main/js/bout.js
Fixed loading more messages when requesting a new page returns an HTML. (Issue #728)
> Fixed loading more messages when requesting a new page returns an HTML. (Issue #728)

- netbout-web/src/main/java/com/netbout/rest/Markdown.java
- netbout-web/src/test/java/com/netbout/rest/MarkdownTest.java
Break line inside a paragraph. (Issue #564)
> Break line inside a paragraph. (Issue #564)

- README.md
Added integration test documentation. (Issue #626)
> Added integration test documentation. (Issue #626)

- netbout-web/src/main/java/com/netbout/rest/TkApp.java
- netbout-web/src/main/java/com/netbout/rest/TkInbox.java
- netbout-web/src/test/java/com/netbout/rest/TkAppTest.java
- netbout-web/src/test/java/com/netbout/rest/TkInboxTest.java
Inbox page search box is searching bouts, see details on #704
> #704 fixed search bouts in inbox page

- netbout-web/pom.xml
- netbout-web/src/main/java/com/netbout/email/EmAction.java
- netbout-web/src/main/java/com/netbout/email/EmCatch.java
- netbout-web/src/main/java/com/netbout/email/EmMessages.java
- netbout-web/src/main/resources/META-INF/MANIFEST.MF
- netbout-web/src/test/java/com/netbout/email/EmActionTest.java
- netbout-web/src/test/java/com/netbout/email/EmCatchTest.java
For #692 
* created an implementation and unit test for EmCatch.Action which should look for the alias by urn and boat_id and post the message into the bout as the author
* added a puzzle to add header Reply-To to an outgoing email
> #692 implementation for EmCatch.Action

- netbout-web/src/main/java/com/netbout/rest/TkStart.java
- netbout-web/src/test/java/com/netbout/rest/bout/TkStartTest.java
For #714
* added rename feature to TkStart
* added a unit test
> #714 added rename feature to TkStart

- netbout-web/src/main/java/com/netbout/rest/TkApp.java
- netbout-web/src/test/java/com/netbout/rest/TkAppTest.java
For #715 
* fixed bug "return after login looses query params"
> #715 fixed return after login looses query params

- netbout-web/src/main/java/com/netbout/rest/TkAppAuth.java
- netbout-web/src/main/resources/META-INF/MANIFEST.MF
- netbout-web/src/test/java/com/netbout/rest/TkAppAuthTest.java
- netbout-web/src/test/resources/META-INF/MANIFEST.MF
For #713 
* add ability to use Basic Authentification according the puzzle description
* added unit test
> #713 added Basic Autentification

- .gitignore
- netbout-web/.bowerrc
- netbout-web/bower.json
- netbout-web/pom.xml
- netbout-web/src/main/bower/postinstall.sh
- netbout-web/src/main/java/com/netbout/rest/TkApp.java
- netbout-web/src/main/xsl/bout.xsl
For Issue #723.
* Added npm and bower to netbout-web project;
* Added to download jquery-textcomplete while generating build;
* Created script to be execute on postinstall hook of bower;
* Thridparty js folder created dynamically with thirdparty javascripts (Also it is supporting JavaScript Source Maps);
> Added to download jquery-textcomplete during build generation (Issue #723)

- netbout-web/pom.xml
For #684
* Takes upgraded to `0.23.3`
> #684 takes 0.23.3

- netbout-web/pom.xml
> #753 removed puzzle

- netbout-web/src/main/java/com/netbout/rest/TkStart.java
- netbout-web/src/test/java/com/netbout/rest/bout/TkStartTest.java
For #784 
* TkStart now allows to use multiple post arguments
* added the unit test
> #784 multiple post arguments in TkStart

- netbout-web/src/main/java/com/netbout/dynamo/DyAttachments.java
for #797 
modified the error message
>  #797 modified the error message

- netbout-web/src/main/java/com/netbout/email/EmCourier.java
- netbout-web/src/main/java/com/netbout/email/EmMessages.java
- netbout-web/src/main/java/com/netbout/email/EmSender.java
- netbout-web/src/test/java/com/netbout/email/EmMessagesTest.java
#736: The error message is displayed in case of email delivery failure when a message is posted.
> #736: The error message is displayed in case of email delivery failure

- netbout-client/src/main/java/com/netbout/client/RtAliases.java
- netbout-client/src/main/java/com/netbout/client/cached/CdAliases.java
- netbout-client/src/main/java/com/netbout/client/retry/ReAliases.java
- netbout-client/src/main/java/com/netbout/mock/MkAliases.java
- netbout-spi/src/main/java/com/netbout/spi/Aliases.java
- netbout-web/src/main/java/com/netbout/cached/CdAliases.java
- netbout-web/src/main/java/com/netbout/dynamo/DyAliases.java
- netbout-web/src/main/java/com/netbout/email/EmAliases.java
- netbout-web/src/test/java/com/netbout/dynamo/DyAliasesITCase.java
for #755 
* modified `Aliases.add()` to return a new instance
* modified all implementation of `Aliases`
>  #755 modified Aliases.add to return a new instance

- netbout-web/pom.xml
for #786 
moved to latest Takes release
> #786 moved to latest Takes release

- netbout-web/pom.xml
#820: (Facebook login doesn't work): Increased the restfb dependency version to 1.15.0.
> #820: Facebook login doesn't work

- netbout-client/src/main/java/com/netbout/mock/MkAttachments.java
- netbout-client/src/main/java/com/netbout/mock/MkBout.java
- netbout-web/src/test/java/com/netbout/rest/TkInboxTest.java
#748: Test case for search bouts.
> #748: Test case for search bouts

- netbout-web/src/test/java/com/netbout/rest/TkInboxTest.java
#748: Removed the puzzle from the code.
> #748: Removed the puzzle from the code

- netbout-web/src/main/java/com/netbout/rest/TkAppFallback.java
- netbout-web/src/test/casperjs/all-pages-are-renderable.js
- netbout-web/src/test/java/com/netbout/rest/TkAppITCase.java
- netbout-web/src/test/java/com/netbout/rest/bout/TkBoutITCase.java
#588: Application Error during access to some pages.
> #588: Application Error during access to some pages

- netbout-web/src/main/java/com/netbout/rest/RqAlias.java
- netbout-web/src/test/java/com/netbout/rest/RqAliasTest.java
For #788 
* modified `RqAlias` to update user's photo from the request
* added a unit test
> #788 fixed bug regards that a new users haven't their avatars 

- netbout-web/src/main/java/com/netbout/rest/TkApp.java
- netbout-web/src/main/java/com/netbout/rest/TkEmVerify.java
- netbout-web/src/main/resources/META-INF/MANIFEST.MF
- netbout-web/src/test/java/com/netbout/rest/bout/TkEmVerifyTest.java
- netbout-web/src/test/resources/META-INF/MANIFEST.MF
#739: Email verification link processing.
> #739: Email verification link processing

- netbout-client/src/main/java/com/netbout/client/RtAlias.java
- netbout-client/src/main/java/com/netbout/client/cached/CdAlias.java
- netbout-client/src/main/java/com/netbout/client/retry/ReAlias.java
- netbout-client/src/main/java/com/netbout/mock/MkAlias.java
- netbout-spi/src/main/java/com/netbout/spi/Alias.java
- netbout-web/src/main/java/com/netbout/cached/CdAlias.java
- netbout-web/src/main/java/com/netbout/dynamo/DyAlias.java
- netbout-web/src/main/java/com/netbout/dynamo/DyFriend.java
- netbout-web/src/main/java/com/netbout/email/EmAlias.java
- netbout-web/src/main/java/com/netbout/rest/TkEmVerify.java
- netbout-web/src/main/java/com/netbout/rest/XeAlias.java
- netbout-web/src/main/java/com/netbout/rest/account/TkSaveEmail.java
- netbout-web/src/test/java/com/netbout/rest/account/TkSaveEmailTest.java
#738: Send email verification link.
> #738: Send email verification link

- netbout-web/src/main/java/com/netbout/rest/bout/TkAttach.java
- netbout-web/src/test/java/com/netbout/rest/bout/TkAttachTest.java
#756: Notification/logging about the attachment uploading.
> #756: Notification/logging about the attachment uploading

- netbout-client/src/main/java/com/netbout/client/RtFriends.java
- netbout-client/src/main/java/com/netbout/client/retry/ReFriends.java
- netbout-client/src/test/java/com/netbout/client/RtFriendsITCase.java
- netbout-spi/src/main/java/com/netbout/spi/Friends.java
For #843 
* Friends#invite() throws UnknownAliasException when/if alias is unknown
* RtFriends#invite() throws UnknownAliasException when/if alias is unknown
* ReFriends#invite() not retry if UnknownAliasException is thrown
* added the unit test
>  #843  fixed missed UnknownAliasException on Friends#invite()

- netbout-client/src/main/java/com/netbout/client/RtFriends.java
- netbout-client/src/main/java/com/netbout/client/retry/ReFriends.java
- netbout-client/src/test/java/com/netbout/client/RtFriendsITCase.java
- netbout-spi/src/main/java/com/netbout/spi/Friends.java
For #844
* Friends#kick() throws UnknownAliasException when/if alias is unknown
* RtFriends#kick() throws UnknownAliasException when/if alias is unknown
* ReFriends#kick() not retry if UnknownAliasException is thrown
* added the unit test
> #844 fixed missed UnknownAliasException on Friends#kick()

- netbout-web/src/test/java/com/netbout/rest/MarkdownPegdownTest.java
> #767 Fix MarkdownTest for Windows environment

- netbout-web/src/main/java/com/netbout/rest/account/TkSaveEmail.java
For #842 as per https://github.com/yegor256/netbout/pull/866#issuecomment-166696213.
> #842 Remove obsolete puzzle from the code

- netbout-web/src/main/java/com/netbout/rest/bout/TkAttach.java
#868 fixed temp file removal on windows machines
> #868 fixed temp file removal on windows machines

- netbout-web/src/main/java/com/netbout/rest/MarkdownTxtmark.java
- netbout-web/src/test/java/com/netbout/rest/MarkdownTxtmarkTest.java
For #889 
* added more tests for the case, when text contains several links
* fixed a bug in the regular expression
>  #889 more tests

- netbout-web/src/main/java/com/netbout/rest/MarkdownTxtmark.java
For #889 
removed the puzzle, the issue fixed already see #906
>  #889 removed puzzle

- .travis.yml
For #908 
PDD and estimates configured in Travis
>  #908 PDD and estimates configured in Travis 

- .travis.yml
for #908 
* got rid PDD verbose output
>  #908 got rid PDD verbose output

- appveyor.yml
> #872 added appveyor config

- netbout-web/pom.xml
for #896 
jcabi-http version bumped up
>  896 jcabi-http version bumped up

- netbout-web/src/main/java/com/netbout/rest/TkInbox.java
- netbout-web/src/main/java/com/netbout/rest/bout/FkBout.java
- netbout-web/src/main/java/com/netbout/rest/bout/TkBout.java
- netbout-web/src/main/xsl/inbox.xsl
#793 added ability to subscribe to bout from home page
> #793 added ability to subscribe to bout from home page

- netbout-web/src/main/xsl/account.xsl
for #860 
* the email attribute value checked before the submiting
> #860 the form allows to submit only new  email

- netbout-web/src/main/xsl/bout.xsl
For #918
* now it's possible to post a new message using CTRL+ENTER combination
> #918 post a new message using ctrl-enter

- netbout-web/src/main/java/com/netbout/rest/Markdown.java
- netbout-web/src/main/java/com/netbout/rest/MarkdownTxtmark.java
- netbout-web/src/test/java/com/netbout/rest/MarkdownTxtmarkTest.java
For #888
* Insert two spaces before a new line symbol to force html line break.
* enabled line break test
* markdown processing switched to TxtMark
> #888 force html line break

- netbout-web/src/main/java/com/netbout/dynamo/DyAlias.java
- netbout-web/src/test/java/com/netbout/dynamo/DyAliasITCase.java
For #938 
* fixed regexp 
* added unit tests
> #938 email validation

- netbout-web/src/main/java/com/netbout/email/EmCourier.java
- netbout-web/src/main/java/com/netbout/email/EmMessages.java
- netbout-web/src/main/java/com/netbout/email/StReplyTo.java
- netbout-web/src/test/java/com/netbout/email/EmMessagesTest.java
#770 Added Reply-To header in emails
> #770 Added Reply-To header in emails

- netbout-web/src/main/java/com/netbout/dynamo/DyAttachment.java
- netbout-web/src/main/java/com/netbout/rest/bout/TkAttach.java
- netbout-web/src/test/java/com/netbout/rest/bout/TkAttachTest.java
#881 Fixed behavior in case of wrong file upload
> #881 Fixed behavior in case of wrong file upload

- netbout-web/src/main/java/com/netbout/rest/account/TkSaveEmail.java
- netbout-web/src/test/java/com/netbout/rest/account/TkSaveEmailTest.java
For #957 
* allows saving the email without the validation when running on the local instance
* added unit tests
> #957 allows saving the email without the validation

- netbout-web/src/main/resources/lang/en.xml
- netbout-web/src/main/xsl/layout.xsl
For #941
-Removed email checking for first page.
> #941 Local Netbout doesn't allow to start a new bout

- netbout-web/src/main/java/com/netbout/rest/TkInbox.java
- netbout-web/src/test/java/com/netbout/rest/TkInboxTest.java
#904 Error handling on invalid 'since' value
> #904 Error handling on invalid 'since' value

- netbout-web/src/main/java/com/netbout/rest/TkEmVerify.java
- netbout-web/src/test/java/com/netbout/rest/bout/TkEmVerifyTest.java
For #932
- Made it possible to catch the error and return a user friendly message.
>  #932 Internal Application Error: EncryptionOperationNotPossibleException

- netbout-web/pom.xml
- netbout-web/src/main/java/com/netbout/rest/XePage.java
- netbout-web/src/main/resources/META-INF/MANIFEST.MF
- netbout-web/src/main/xsl/layout.xsl
- netbout-web/src/test/java/com/netbout/rest/TkAppITCase.java
- netbout-web/src/test/resources/META-INF/MANIFEST.MF
For issue #878 
- added meta `description` tag
- no need to add `title` as it is already in-place
> #878 add meta description tag

- netbout-web/src/main/xsl/bout.xsl
#978 remove trailing space in message field
> Text form starts with a space

- netbout-web/src/main/java/com/netbout/rest/MarkdownTxtmark.java
for #986 
We need more information to reproduce the bug so caught the exception as workaround for now
> #986 catch exception

- .pdd
- netbout-client/src/main/java/com/netbout/client/RtBout.java
- netbout-web/src/main/java/com/netbout/dynamo/DyInbox.java
- netbout-web/src/main/java/com/netbout/email/EmAlias.java
For #981
- Added .pdd file and configurations.
> #981 PDD check on Travis is not working for pom.xml 

- netbout-web/src/main/java/com/netbout/rest/MarkdownTxtmark.java
- netbout-web/src/test/java/com/netbout/rest/MarkdownTxtmarkTest.java
For : #863
- Fixed pattern to recognize reference style
> #863 Fixed Reference-style markdown images do not work in bouts 

- .rultor.yml
- .travis.yml
For #981
- Removed  duplicated source and verbose property
> #981  New issue PDD check on Travis is not working for pom.xml 

- netbout-web/src/main/js/bout.js
[#995](https://github.com/yegor256/netbout/issues/995) fix
>  Autocompletion doesn't filter #995 

- netbout-web/src/main/java/com/netbout/rest/account/TkSaveEmail.java
- netbout-web/src/test/java/com/netbout/rest/account/TkSaveEmailTest.java
for #1015 
* fixes the definition of the Netbout local mode
* changed the test
> #1015 fixes the definition of the Netbout local mode

- netbout-client/pom.xml
- netbout-client/src/main/java/com/netbout/client/RtBout.java
- netbout-client/src/main/java/com/netbout/mock/MkAttachment.java
- netbout-client/src/main/java/com/netbout/mock/MkAttachments.java
- netbout-client/src/test/java/com/netbout/client/RtAliasITCase.java
- netbout-client/src/test/java/com/netbout/client/RtAttachmentsITCase.java
- netbout-client/src/test/java/com/netbout/client/RtBoutITCase.java
- netbout-client/src/test/java/com/netbout/client/RtUserITCase.java
- netbout-client/src/test/java/com/netbout/mock/MkAttachmentsTest.java
- netbout-client/src/test/java/com/netbout/mock/MkInboxTest.java
- netbout-client/src/test/java/com/netbout/mock/TouchBoutTest.java
- netbout-web/src/main/java/com/netbout/Launch.java
- netbout-web/src/main/java/com/netbout/dynamo/DyAlias.java
- netbout-web/src/main/java/com/netbout/dynamo/DyAttachment.java
- netbout-web/src/main/java/com/netbout/dynamo/DyInbox.java
- netbout-web/src/main/java/com/netbout/email/BoutInviteMail.java
- netbout-web/src/main/java/com/netbout/email/EmAlias.java
- netbout-web/src/main/java/com/netbout/email/EmCatch.java
- netbout-web/src/main/java/com/netbout/rest/Markdown.java
- netbout-web/src/main/java/com/netbout/rest/TkApp.java
- netbout-web/src/main/java/com/netbout/rest/bout/TkDownload.java
- netbout-web/src/main/java/com/netbout/rest/bout/XeAttachment.java
- netbout-web/src/main/java/com/netbout/rest/login/TkRegister.java
- netbout-web/src/test/java/com/netbout/rest/MarkdownTxtmarkTest.java
- netbout-web/src/test/java/com/netbout/rest/TkAppITCase.java
- netbout-web/src/test/java/com/netbout/rest/TkInboxTest.java
- netbout-web/src/test/java/com/netbout/rest/bout/TkInviteTest.java
- netbout-web/src/test/java/com/netbout/rest/bout/TkStartTest.java
- pom.xml
For #1013 
- Updated qulice to 0.16.2.
- Fixed checkstyle,pmd violations.
> #1013 Upgrade qulice to 0.16.2

- est/003.est
> Re-estimate project size

- Procfile
> #timeout: timeout 60 seconds

- pom.xml
for #1032 ignored coveralls errors
>  #1032 ignore coveralls error

- pom.xml
>  #1032 removed timestamp property

- .rultor.yml
>  #1032 turn off coveralls profile

- netbout-client/pom.xml
- netbout-spi/pom.xml
>  #1032 site-maven-plugin version

- .rultor.yml
>  #1032 turn off site-deploy

- netbout-web/src/main/scss/bout.scss
For  #859
- Changed scss style.
>  #859 Visual glitches when using markdown titles in bouts

- netbout-web/pom.xml
- netbout-web/src/main/java/com/netbout/rest/Markdown.java
- netbout-web/src/main/java/com/netbout/rest/MarkdownPegdown.java
- netbout-web/src/test/java/com/netbout/rest/MarkdownPegdownTest.java
- netbout-web/src/test/java/com/netbout/rest/TkPreviewTest.java
> #1045 shifted back to PegDown

- netbout-web/src/main/js/bout.js
- netbout-web/src/main/scss/bout.scss
For #857
- Disabled upload button if there is no file selected.
> #857 Pressing 'Upload' without attachment chosen redirects to home page 

- netbout-web/pom.xml
for #1045 
upgraded AWS dependencies to the latest version
>  #1045 upgraded aws libs

- netbout-web/src/main/js/bout.js
- netbout-web/src/test/casperjs/bout-rename-to-empty.js
Fixes for #862:
- Modified bout.js to prevent renaming with an empty string.
> #862 prevented bout renaming to empty string

- .rultor.yml
- pom.xml
#1032: added timestamp format for coveralls-maven-plugin
> Coveralls maven plugin can't parse a date

- netbout-web/src/main/java/com/netbout/rest/MarkdownTxtmark.java
- netbout-web/src/test/java/com/netbout/rest/MarkdownTxtmarkTest.java
For #858
- Enabled safe mode
Now it looks like this :
> #858 XSS vulnerability in bouts 

- netbout-web/src/main/java/com/netbout/cached/CdBout.java
- netbout-web/src/main/java/com/netbout/cached/CdUser.java
see #1045 
extra caching, should help
> #1045 extra caching

- .rultor.yml
for #1032 
turn off site deployment due  to #1055
>  #1032 turn off site deployment due  to #1055

- pom.xml
#1055: : changed coveralls trigger, added cobertura profile, updated cobertura, coveralls versions
> #1055: Cobertura-maven-plugin doesn't generate xml report

- netbout-web/src/main/java/com/netbout/rest/TkApp.java
- netbout-web/src/main/java/com/netbout/rest/TkWithAliasHeader.java
- netbout-web/src/test/java/com/netbout/rest/TkAppTest.java
For  #828
- Added header to every authorized response.
- Updated test to see if the header is added.
>  #828 X-Netbout-Alias

- netbout-web/.bowerrc
- netbout-web/pom.xml
- netbout-web/src/main/bower/postinstall.sh
#849: delegated bower's postinstall to maven
> Build fails on Windows during 'bower install' phase when frontend-maven-plugin is executed

- netbout-web/pom.xml
- netbout-web/src/test/java/com/netbout/rest/TkAppTest.java
For #1038 
* upgraded to latest takes
* fixed tests according to https://github.com/yegor256/takes/issues/642
> #1038 upgraded to latest takes, fixed tests

- netbout-client/src/main/java/com/netbout/client/RtInbox.java
- netbout-client/src/main/java/com/netbout/mock/MkInbox.java
- netbout-client/src/test/java/com/netbout/client/RtInboxITCase.java
- netbout-web/src/main/java/com/netbout/dynamo/DyInbox.java
- netbout-web/src/test/java/com/netbout/rest/TkInboxTest.java
Fixes for #856:
- Included bout titles in searching logic.
- Included in unit test.
- Added integration test.
> #856 Included bout titles in searching logic.

- netbout-client/src/main/java/com/netbout/mock/MkAlias.java
- netbout-web/src/main/java/com/netbout/email/EmAlias.java
- netbout-web/src/main/java/com/netbout/rest/account/TkSaveEmail.java
- netbout-web/src/test/java/com/netbout/rest/account/TkSaveEmailTest.java
- netbout-web/src/test/java/com/netbout/rest/bout/TkInviteTest.java
#1080
changed exception type, so stack trace not to be shown in browser.
> #1080 hide stack trace for invalid email

- pom.xml
for  #1045 
upgraded jcabi-aspect to latest release
>  #1045 upgraded jcabi-aspect to latest release

- netbout-client/src/main/java/com/netbout/client/RtAttachment.java
- netbout-client/src/test/java/com/netbout/client/RtAttachmentsITCase.java
- netbout-web/src/main/java/com/netbout/dynamo/DyAttachment.java
- netbout-web/src/main/java/com/netbout/dynamo/DyAttachments.java
- netbout-web/src/main/java/com/netbout/rest/bout/XeAttachment.java
Implementations for #1090:
- Added Attachment creation date to DynamoDB.
- Added Attachment creation date to Xembly generated files.
- Enabled integration tests for attachment creation date.
> #1090 Creation date added to Dy/Xe/RtAttachment and tests

- netbout-web/pom.xml
- netbout-web/src/main/java/com/netbout/dynamo/DyAttachment.java
- netbout-web/src/test/java/com/netbout/dynamo/DyAttachmentsITCase.java
for #1100
upgrade jcabi-s3 to latest version
> #1100 upgrade jcabi-s3 to latest version

- netbout-web/src/main/java/com/netbout/dynamo/DyAttachment.java
> #1103 quick fix  for not existing attribute

- est/004.est
PR for issue #1095 .
4th project re-estimation
> Project estimation

- .github/workflows/codecov.yml
- .simplecov
- Gemfile
- Gemfile.lock
- LICENSE.txt
- README.md
- liquibase/2024/001-initial-schema.xml
- liquibase/2024/002-guests.xml
- liquibase/2024/003-token.xml
- liquibase/master.xml
- Enable codecov check on PR creation
- add codecov label 
- small fixes
Fix #1207
> [#1207] Enable codecov check in PR creation
