netbout-web/src/test/java/com/netbout/rest/MarkdownTest.java

Added replacement of `\n` with platform-dependent line.separator. Tested locally by running with `mvn clean install -Pqulice -Dline.separator=$'\r\n'`

#604 MarkdownTest fails on Windows

---

netbout-web/src/main/java/com/netbout/rest/RsReturn.java
netbout-web/src/main/java/com/netbout/rest/TkApp.java
netbout-web/src/main/java/com/netbout/rest/TkReturn.java
netbout-web/src/test/java/com/netbout/rest/TkAppTest.java

Proposed fix for issue #609.
* New classes `RsReturn` and `TkReturn` are added, similar to `RsFlash`/`TkFlash`
* Anonymous request to any location except `/` uses `RsReturn` to store the location in a cookie and redirects to `/`
* Authenticated request to `/` uses `TkReturn` to check whether there is a return cookie, and if so, sends redirect to return location and clears cookie

#609 return after login

---

netbout-web/src/main/java/com/netbout/rest/Markdown.java
netbout-web/src/test/java/com/netbout/rest/MarkdownTest.java

Suggested fix for issue #581. Regex is used to find links outside of markdown format and wrap them into markdown-formatted links (i.e. `[foo](bar)`). Test verifies that text with plain links produces correct HTML and that text with properly-formatted links is not corrupted.

#581 plain link detection in messages

---

netbout-web/src/main/java/com/netbout/rest/Markdown.java
netbout-web/src/test/java/com/netbout/rest/MarkdownTest.java

Fix for issue #664. Instead of complexifying the regex I've implemented 'manual' check of text before and after link to make sure we are not inside markdown syntax.

#664 Disable link detection inside markdown syntax

---

netbout-web/src/main/java/com/netbout/email/EmMessages.java
netbout-web/src/main/java/com/netbout/email/GmailViewAction.java
netbout-web/src/test/java/com/netbout/email/EmMessagesITCase.java

Added HTML code to generate the ViewAction in Gmail as per documentation:
https://developers.google.com/gmail/markup/reference/go-to-action#view_action
Tests performed only by manually printing the mail message.
We need a way to test real mail, or if already there a proper documentation on how to do it.
I will raise an issue on that.
Fixes #546

#546 'View Bout' action in Gmail

---

netbout-client/src/main/java/com/netbout/client/RtBout.java
netbout-client/src/main/java/com/netbout/client/cached/CdBout.java
netbout-client/src/main/java/com/netbout/client/retry/ReBout.java
netbout-client/src/main/java/com/netbout/mock/MkBout.java
netbout-client/src/main/java/com/netbout/mock/MkFriends.java
netbout-spi/src/main/java/com/netbout/spi/Bout.java
netbout-web/src/main/java/com/netbout/cached/CdBout.java
netbout-web/src/main/java/com/netbout/dynamo/DyBout.java
netbout-web/src/main/java/com/netbout/email/EmBout.java
netbout-web/src/main/java/com/netbout/email/EmMessages.java

This PR fixes #682 puzzle:
>Send email if friend subscribed to bout. Friend should be filtered before send email by subscription
It overloads `subscription` call with `String alias` argument to be able to see if subscription is enabled for particular alias within target bout.

Fixed #682 puzzle

---

netbout-web/src/main/java/com/netbout/rest/Markdown.java
netbout-web/src/test/java/com/netbout/rest/MarkdownTest.java

Fixed whitespace that was missing after a link.
It was necessary to use a regular expression because JTIDY is configured to import and export the content as XML and this causes that after a "END NODE" the library removes all whitespace characters.

Fixed whitespace that was missing after a link. (Issue #671)

---

README.md
netbout-client/src/test/java/com/netbout/client/NbRule.java

read `netbout.url` from system property
netbout-client integration tests will communicate with netbout server in `netbout.url`
this solved the problem mentioned in #776

read netbout.url from system property

---

netbout-client/src/main/java/com/netbout/client/RtAttachment.java
netbout-client/src/test/java/com/netbout/client/RtAttachmentsITCase.java

For #717 
* modified RtAttachment to be able handle a binary content
* modified the unit test

 #717 fixes RtAttachment#write() breaks the content 

---

netbout-web/src/main/java/com/netbout/cached/CdBout.java
netbout-web/src/test/java/com/netbout/email/EmMessagesITCase.java

https://github.com/yegor256/netbout/issues/695
The issue happens because the CdBout class casches a subscription in invalid way.
See https://github.com/yegor256/netbout/blob/master/netbout-web/src/main/java/com/netbout/cached/CdBout.java#L106
Namely, this class isn't singleton and both accounts have their instance of class.
When account 2 subscribes herself/himself (step 2 or 4), he/she will reset a cache (CdBout.subscription(String alias) in his/her instance of class.
It will not affect the instance this class of account 1.
You will check that with additional step:
- account 1 turns off (she/he can after that turn on the subscription) the subscription (the bell icon)
Now, when account 1 post a message, account 2 will be notified (or not) according his/her subscription settings. …

Issue #695 - the subscription status frozen

---

netbout-web/src/main/java/com/netbout/email/BoutInviteMail.java
netbout-web/src/main/java/com/netbout/email/EmAlias.java
netbout-web/src/main/java/com/netbout/email/EmCourier.java
netbout-web/src/main/java/com/netbout/rest/Markdown.java
netbout-web/src/main/java/com/netbout/rest/MarkdownPegdown.java
netbout-web/src/main/java/com/netbout/rest/bout/TkPreview.java
netbout-web/src/main/java/com/netbout/rest/bout/XeAttachment.java
netbout-web/src/main/java/com/netbout/rest/bout/XeMessage.java
netbout-web/src/test/java/com/netbout/rest/MarkdownPegdownTest.java

For #847 
* introduced Markdown interface to convert Markdown-formatted text to its html representation
* Previous `Markdown` with PegDown implementation renamed to  MarkdownPegDown
* Created a new puzzle to implement MarkdownTxtmark

#847 Markdown interface introduced

---

netbout-web/src/main/java/com/netbout/rest/XeAlias.java
netbout-web/src/main/resources/lang/en.xml
netbout-web/src/main/scss/layout.scss
netbout-web/src/main/xsl/layout.xsl

Original warning:
Now there is new warning whenever email is not yet verified (contains `!`):
Tootip with explanation is displayed when mouse is over the warning area.
Is any additional testing needed? I haven't found any existing tests to the similar features.
Fixes #842.

#842 Show exclamation icon when email is not verified

---

netbout-web/src/main/java/com/netbout/cached/CdInbox.java
netbout-web/src/test/java/com/netbout/cached/CdInboxTest.java

For #787:
* flushing cache
* test to confirm that caches are cleared and `CdInbox.unread()` do not provide stale value whenever Inbox is refreshed

#787 Clear unread messages cache when reading

---

netbout-web/pom.xml
netbout-web/src/main/java/com/netbout/rest/MarkdownTxtmark.java
netbout-web/src/test/java/com/netbout/rest/MarkdownTxtmarkTest.java

For #873
* implemented MarkdownTxtMark
* turned on the unit tests. TxtMark produces more correct html code than Pegdown, that's why I have made some corrections in the unit tests

#873 implemented MarkdownTxtMark

---

netbout-client/pom.xml
netbout-client/src/test/java/com/netbout/client/NbRule.java

As a fix for #791 , I've added the `parallelTestsTimeoutInSeconds` parameter to the `pom.xml` in `netbout-client`. As a result, any network issues causing long delays in the test cases will not affect the build process.
**EDIT**
Made a permanent fix to freeze issue by removing the `ReUser` wrapper class. However, I still think that parallel tests timeout is needed as an overall check in `pom.xml` (though I've removed it for the time being).

#791 Introduced parallel tests timeout

---

netbout-client/pom.xml

#900 upgraded netbout-client dependencies:
jcabi-http  1.10.4 -> 1.14.1    
h2  1.4.186 -> 1.4.190 
jersey-client   1.18.1 -> 1.19

#900 upgraded netbout-client dependencies

---

netbout-web/pom.xml
pom.xml

For #812:
*  updated jcabi-aspects to 0.22.3
* rest of updates were needed to make build passing for various reasons (mainly lack of compatibility)

#812 Update jcabi-aspects to the latest version

---

netbout-web/src/main/scss/preview.scss

For #883
-Added width to the .container scss class, this tells the container to take 100% of the width.

#883 Frame for code in preview is too wide and causes visual glitch

---

netbout-web/pom.xml
netbout-web/src/main/java/com/netbout/rest/TkStart.java

This is a fix for issue #750. What has changed:
- Added a check for `token` querystring parameter in `TkStart.java`.
- If token param is empty, proceeds to create a new bout as usual.
- If token param is not empty, searches it in the cache.
- If found in cache, gets the bout from there instead of creating new one.
- If not found in cache, creates a new bout and adds it to cache.

fix for issue #750; added check for token parameter

---

netbout-web/src/main/java/com/netbout/dynamo/DyAlias.java
netbout-web/src/main/java/com/netbout/rest/account/TkSaveEmail.java
netbout-web/src/test/java/com/netbout/dynamo/DyAliasITCase.java

for #947 
* fixed regexp for the case when email was be empty before the changing
* added unit tests
* created a new puzzle to disable the email validation when Netbout running localy.
it doesn't make sense to send a verification link when we haven't access to email server

947 fixed the email validation

---

netbout-web/src/main/java/com/netbout/rest/TkStart.java
netbout-web/src/test/java/com/netbout/rest/bout/TkStartTest.java

For #954 
- added test case for token handling
- since #750 is not fully resolved, the test case is set as ignored and puzzle added

#954 Add unit tests to test scenarios for requests with/without a token

---

.rultor.yml
.travis.yml
netbout-client/src/site/apt/index.apt.vm
netbout-spi/src/site/apt/index.apt.vm
netbout-web/src/main/js/bout.js
netbout-web/src/main/js/friends.js
netbout-web/src/site/apt/index.apt.vm
src/site/apt/index.apt.vm
years.sh

Fixes #943: check for CI and rultor for years in copyright by greping trough all files that have a copyright if the years are set correct and add this to the build scripts

#943 - added check for correct copyright years (2009 - current)

---

.rultor.yml
netbout-web/pom.xml

This is a fix for issue #898.
What has changed:
- Upgraded `site-maven-plugin` to `v0.12` in pom.xml.
- site-deployment enabled in `.rultor.yml`.

Fix for issue #898

---

netbout-web/src/main/java/com/netbout/dynamo/DyMessages.java
netbout-web/src/test/java/com/netbout/dynamo/DyMessagesITCase.java

For issue #945 
- don't strip leading spaces as four spaces are treated as `code` markdown

#945 keep leading spaces for code markdown

---

netbout-web/package.json
netbout-web/pom.xml
years.sh

Handles bug #914 by installing a package.json that specifies the dependency to bower. npm then decides itself if a reinstall is necessary.

#914 netbout-web installs bower each time it is built

---

netbout-web/src/main/java/com/netbout/rest/MarkdownTxtmark.java
netbout-web/src/test/java/com/netbout/rest/MarkdownTxtmarkTest.java

for #986
* fixed bug related to unquoted characters like `\` and `$` from Markdown input

 #986 quoted replacements

---

netbout-web/src/main/java/com/netbout/rest/bout/TkInvite.java
netbout-web/src/test/java/com/netbout/rest/bout/TkInviteTest.java

added test for invite of too long alias and corrected TkInvite::act

Trying to invite alias with long string causes not handled exception #864

---

netbout-client/src/main/java/com/netbout/mock/H2Sql.java

Fix for #963 
- Marked the files created by the H2Sql class to be deleted on exit.

Fix for #963 - Delete temporary files created by the H2Sql class

---

netbout-web/src/main/java/com/netbout/rest/MarkdownTxtmark.java
netbout-web/src/test/java/com/netbout/rest/MarkdownTxtmarkTest.java

for #997 
* fixed the html links detection regexp to ignore spaces after a inline link
* added unit tests

#997 ignored space after inline link

---

netbout-client/src/main/java/com/netbout/mock/MkBout.java
netbout-spi/src/main/java/com/netbout/spi/Friends.java
netbout-web/src/main/java/com/netbout/dynamo/DyBout.java
netbout-web/src/main/java/com/netbout/rest/bout/TkInvite.java
netbout-web/src/test/java/com/netbout/rest/bout/TkInviteTest.java

for #1023 
* created a new `Friends` decorator `ValidFriends` that validates the alias name before using it
* moved the checking  form TkInvite to `DyFriends` and `MkFriends`
* created a new unit test

#1023  fixed incorrect checking of a alias name

---

.rultor.yml

For #992
- Added clean install to the last command because just removing clean did not work.

#992 Deployment failed due to the coverage report not exists

---

netbout-web/src/main/java/com/netbout/rest/TkAppFallback.java
netbout-web/src/test/java/com/netbout/rest/TkAppITCase.java

This solves #998 :
* Turned notice from success typo to severe type
* Same logic used as in RsFailure, but adding the LEVEL.SEVERE to the RsFlash
* Tightened up the exception type according to what this change allows
* Added checking the xPath, including of the class the red notice, to in the existing test for "404s"
Now looks like this:

#998 turned missing page notice into severe type instead of success

---

netbout-web/src/main/java/com/netbout/rest/bout/TkKick.java
netbout-web/src/test/java/com/netbout/rest/bout/TkBoutITCase.java

This solves #875 
Fixed by:
* Handling the unknown `Friends.UnknownAliasException` where unknown attachment names are handled already
* Added integration test case
Now looks the way it should imo:

#875 exception from kicking a non-existant user from a bout is properly handled

---

pom.xml

For #850
- Incorporated file encoding in the POM.

#850 Multiple tests do not work on Windows due to encoding set to 'windows-1250' by default 

---

Procfile

see #1045 
This should turn JMAP dumps on. I configured S3 deployments already, as explained here: https://devcenter.heroku.com/articles/java-memory-issues#generating-heap-dumps-in-the-background

#1045: jmap configured

---

netbout-web/src/main/java/com/netbout/cached/CdAlias.java
netbout-web/src/test/java/com/netbout/rest/account/TkSaveEmailTest.java

#853 is resolved by this.
Admittedly a minimal fix/reproduce, but I think it will work in production.
This should also resolve #721 which is a duplicate of #853 as well as #989 to some degree.
PR does:
* Turn off caching for emails
* Adds a test for the situation of cached emails, failing without the removal of caching.
* This is kind of needed for a lack of a better ache invalidation strategy I fear: While it's not a big issue when say the information of what is unread and what is not is cached like this:
```
@Cacheable(lifetime = Tv.FIVE, unit = TimeUnit.MINUTES)
public long unread() throws IOException {
return this.messages.unread();
}
```
(ok this is a little meh in terms of usability at present, always seems like you missed reading a tab :D) ... for emails it gets us in the …

#853 minimal fix and test to reproduce the issue

---

README.md
netbout-web/pom.xml

#851 is resolved by this.
PR looks bigger than it is:
* Created new profile `casperjs` that does nto run when tests are skipped
* Moved all casperjs related things ( install and test run ) in there
* Made the requirements for local run via the `hit-refresh` profile load per default
* I think this is ok now, given that we only load the things for local run, not the casperjs install since I moved it out of the takes-test block
* Renamed profile `takes-test` to `takes-setup` since this does not invoke the casperjs tests like it did before anymore now

#851 local Netbout setup runs without requiring tests to be run beforehand

---

pom.xml

#1069: updated com.github.github:site-maven-plugin version  to 0.12, downgraded cobertura version  to 2.6 (#1065 [comment](https://github.com/yegor256/netbout/pull/1065#issuecomment-191423258))

#1069: upgrade github maven plugin

---

netbout-web/src/main/java/com/netbout/rest/MarkdownTxtmark.java
netbout-web/src/test/java/com/netbout/rest/MarkdownTxtmarkTest.java

#952 - Fixed preview for code blocks.
- Updated MarkdownTxtmark to iterate through input text and add trailing spaces (for line breaks) only for fragments outside code blocks to avoid invalid br elements;
- Updated MarkdownTxtmark class with methods for inserting html pre elements where needed to display line breaks in code fragments;
- Added test method to MarkdownTxtmark for testing code blocks.

#952 - Fixed preview for code blocks marked with ```

---

netbout-client/src/main/java/com/netbout/client/RtAttachment.java
netbout-client/src/main/java/com/netbout/client/cached/CdAttachment.java
netbout-client/src/main/java/com/netbout/client/retry/ReAttachment.java
netbout-client/src/main/java/com/netbout/mock/H2Sql.java
netbout-client/src/main/java/com/netbout/mock/MkAttachment.java
netbout-client/src/test/java/com/netbout/client/RtAttachmentsITCase.java
netbout-client/src/test/java/com/netbout/mock/MkAttachmentsTest.java
netbout-spi/src/main/java/com/netbout/spi/Attachment.java
netbout-web/src/main/java/com/netbout/cached/CdAttachment.java
netbout-web/src/main/java/com/netbout/dynamo/DyAttachment.java
netbout-web/src/main/java/com/netbout/email/EmAttachment.java
netbout-web/src/main/java/com/netbout/rest/bout/XeAttachment.java
netbout-web/src/test/java/com/netbout/dynamo/DyAttachmentITCase.java

Fixes for #839:
- Added author() and date() methods to Attachment.
- Implemented those methods in all Attachment implementations.
- Added Unit and Integration tests.
- Added new puzzle in `DyAttachmentITCase`

#839 Added author() and date() to Attachment and implementations.

---

netbout-web/src/main/scss/layout.scss
netbout-web/src/main/xsl/inbox.xsl
netbout-web/src/test/casperjs/inbox-noresults-message.js

This is for issue #855  .
Modified the display conditions in ``inbox.xsl`` . If we have no bouts to display, we check if the query was empty.
**If it was empty** (so no search was performed by the user - the inbox page is simply opened) then we show the "welcome" text with ``Someone invited you here? ... ``
**else, if the query is not empty** then we show a red message saying ``No bouts found for query "given query"``
It's done like this since a search is performed anyway at each page load: either the user made a search and the page loads with the given query, or the page is loaded with no query and the search is performed for all (``*``) bouts.
cc: @mkordas Pls let me know if this behavior is what you want. I see no reason for a reviewer to not accept this so I'm asking you directly to …

Message in case of no results for search

---

netbout-client/src/test/java/com/netbout/client/NbRule.java
netbout-client/src/test/java/com/netbout/client/RtFriendsITCase.java
pom.xml

PR for #1119 .
Other changes: Added one more assumption, since apparently maven-failsafe-plugin 2.19 reads null system properties as empty strings and ``mvn clean install -Pqulice`` would fail because of IT tests
E.g.
```
...
<artifactId>maven-failsafe-plugin</artifactId> 
<configuration>
<systemPropertyVariables>
<netbout.token>${netbout.token}</netbout.token>
</systemPropertyVariables>
</configuration>
...
```
^ Before, the sys variable was set null, now it's set empty string and the IT tests faile without the new assumption.

Updated jcabi-parent

---

netbout-web/src/main/java/com/netbout/email/EmAlias.java
netbout-web/src/test/java/com/netbout/email/EmAliasTest.java

PR for #841 .
Added a more detailed verification email message and wrote unit test.
This is how the verification email will look: 
***
<p>Hi,<br />Your notification e-mail address for <a href="http://www.netbout.com">netbout</a> has been changed. Please verify it by clicking <a href="netbout.com/test/verification/link">here</a>.</p>
If you did not change your e-mail address you can ignore this message <br/>This is an automated e-mail, please do not reply. If you have any questions, submit an issue <a href="https://www.github.com/yegor256/netbout">here</a><br/><br/> Best regards,<br/>Netbout team
***
When constructing the message inside ``EmAlias.email(...)`` I would have used ``new Markdown.Default().html([here](...link...))`` for all the anchors, but ``Markdown.html()`` puts everything …

Detailed e-mail confirmation message and unit test
